### ISSUE TITLE
HW4 problem 3 - avg(radius) or avg(area)?

### ISSUE THREAD

**Issue by zeruniverse** [IACS-CS-207/cs207-F17#2]
The question said we should calculate `avg(radius)` while the hints suggest to store all areas. Are we supposed to calculate `avg(radius)` or `avg(area)`?

**Comment by dsondak** [comment]
HI Jeffery,

    The question statement says that you should calculate the average area.

Best,

D.Sondak

**Comment by zeruniverse** [comment]
Then it might be a typo in Question 3 statement

1.) The first function should return the average **circle radius**

**Comment by dsondak** [comment]
Fixed the typo.
